apiVersion: v1
kind: Service
metadata:
  name: tutorial
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    com.docker.project: tutorial
  type: LoadBalancer
status:
  loadBalancer: {}
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.docker.project: tutorial
  name: tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      com.docker.project: tutorial
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        com.docker.project: tutorial
    spec:
      containers:
      - image: hellodocker
        imagePullPolicy: IfNotPresent
        name: hello
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "250m"
            memory: "64Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"
      restartPolicy: Always
