apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: dynamodb-with-bucket
spec:
  compositeTypeRef:
    apiVersion: tdeheurles.com/v1alpha1
    kind: database
  resources:
    - name: s3Bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        metadata:
          name: crossplane-quickstart-bucket
        spec:
          providerConfigRef:
            name: default
      patches:
        - fromFieldPath: "spec.region"
          toFieldPath: spec.forProvider.region
          transforms:
            - type: map
              map:
                ireland: "eu-west-1"
                london: "eu-west-2"
                paris: "eu-west-3"
    - name: dynamoDB
      base:
        apiVersion: dynamodb.aws.upbound.io/v1beta1
        kind: Table
        metadata:
          name: crossplane-quickstart-database
        spec:
          forProvider:
            writeCapacity: 1
            readCapacity: 1
            attribute:
              - name: S3ID
                type: S
            hashKey: S3ID
      patches:
        - fromFieldPath: "spec.region"
          toFieldPath: spec.forProvider.region
          transforms:
            - type: map
              map:
                ireland: "eu-west-1"
                london: "eu-west-2"
                paris: "eu-west-3"
