apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xenvams.tdeheurles.com
spec:
  group: tdeheurles.com
  names:
    kind: xenvam
    plural: xenvams
  claimNames:
    kind: envam
    plural: envams
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
